export const spTestData = {
  columns: [
    { title: 'Title/Subject of RFP', field: 'title', sorter: 'string' },
    { title: 'Procurement Status', field: 'status', sorter: 'string' },
    { title: 'Procurement Number', field: 'number', sorter: 'string' },
    { title: 'Magic Contract #', field: 'magicContract', sorter: 'string' },
    { title: 'MDHS Division', field: 'division', sorter: 'string' },
    { title: 'Federal Program', field: 'program', sorter: 'string' },
    { title: 'Purpose', field: 'purpose' },
    {
      title: 'Issue Date',
      field: 'issue',
      sorter: 'date',
      sorterParams: {
        format: 'M/d/YYYY',
      },
    },
    {
      title: 'Expiration Date',
      field: 'expiration',
      sorter: 'date',
      sorterParams: {
        format: 'M/d/YYYY',
      },
    },
    {
      title: 'Effective Date',
      field: 'effective',
      sorter: 'date',
      sorterParams: {
        format: 'M/d/YYYY',
      },
    },
    { title: 'Award Amount', field: 'amount' },
    { title: 'Attachments', field: 'attachments' },
    { title: 'Procurement Type', field: 'type' },
  ],
  rows: [
    {
      id: 1,
      title: 'Model Procurement 1',
      status: 'Open Solicitation',
      number: '12305K',
      magicContract: '1234567890E',
      division: 'Workforce Development',
      program: 'TANF',
      purpose: 'The purpose of this RFP is to request proposals for the development of a new workforce program. ',
      issue: '10/1/2023',
      expiration: '',
      effective: '',
      amount: '',
      attachments: '',
      type: '',
    },
    {
      id: 2,
      title: 'Model Procurement 2',
      status: 'Awarded',
      number: '12325647',
      magicContract: '42356871P',
      division: 'Aging and Adult Services',
      program: 'AAA',
      purpose: 'Testing the procurement system list.',
      issue: '9/13/2023',
      expiration: '9/29/2023',
      effective: '11/1/2023',
      amount: '25,000',
      attachments:
        'https://mdhsmsgov-my.sharepoint.com/personal/claire_graves_mdhs_ms_gov/Lists/Procurements%20for%20MDHS%20Website/Attachments/2/wow.png?web=1',
      type: '',
    },
    {
      id: 3,
      title: 'Model Procurement 3',
      status: 'Closed',
      number: '1231561',
      magicContract: '452168R',
      division: 'Workforce Development',
      program: 'TANF',
      purpose: 'Testing our new system.',
      issue: '8/1/2023',
      expiration: '',
      effective: '',
      amount: '',
      attachments: '',
      type: '',
    },
  ],
};
